### ISSUE TITLE
Pump unreachable. Reset AAPS and RL and while Omnipod status would state connected there would be no communication with pod. Had to rest pod to remove as deactivation would not work

### ISSUE THREAD

**Issue by ohjay73** [AAPS-Omnipod/AndroidAPS-OLD#84] opened 2020-02-08 16:51 UTC
[AndroidAPS_LOG_1581179817081.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4174665/AndroidAPS_LOG_1581179817081.log.zip)
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by ohjay73** [comment] 2020-02-08 16:52
Issue started ~ 0920 MT logs attached

**Comment by andyrozman** [comment] 2020-02-15 11:00
No logs attached and it seems to be duplicate of #83

**Closed as completed by andyrozman** 2020-02-15 11:00 UTC
Labels: Duplicate

**Comment by ohjay73** [comment] 2020-02-15 14:32
@andyrozman logs are in the first post AndroidAPS_LOG_1581179817081.log.zip
Reporting bugs
