### ISSUE TITLE
Just received an uncertain failure in pod history while driver tried to set a tbr

### ISSUE THREAD

**Issue by Kaivish** [AAPS-Omnipod/AndroidAPS-OLD#101] opened 2020-03-03 20:29 UTC
Started to get new hiccups with 0.2. 
Several time today aaps just froze and stopped responding while giving a meal bolus. Progress bar stuck on waiting for pump, but pod clicks and delivers the bolus. Aaps have to be force closed to get running again. Toggling bt off/on helps sometimes. 
Second issue is i noticed a uncertain failure in pod history while driver tried to set tbr then give smb. 
Timeline for that is 21.05.55
Uploading screen and logs. 

[AndroidAPS_LOG_1583266089588.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4283434/AndroidAPS_LOG_1583266089588.log.zip)

![IMG_20200303_210755](https://user-images.githubusercontent.com/41928579/75816647-ddbeca00-5d95-11ea-8d71-035f49587166.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by bartsopers** [comment] 2020-03-03 21:34
These happen occasionally. It's not a bug, or at least not something we can fix. Closing this issue.

**Closed as completed by bartsopers** 2020-03-03 21:34 UTC
