### ISSUE TITLE
Pump unreachable - needed AAPS restart to solve.

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#83] opened 2020-01-30 00:12 UTC
AndroidAPS 2.6-omnipod-0.2
Build EROS_0.2 (release)

### Problem:
1st time I actually lost connection to Pod. Finally found out after beeing disconnected for 45 min when trying to bolus which failed (Beep/Mute/Ignore?)

Pod status refreshing did not solve..... finally after restarting AAPS (UI->exit) connection was restored

### Additional info:
[AndroidAPS_LOG_1580332137145.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4131513/AndroidAPS_LOG_1580332137145.log.zip)
![Screenshot_20200129-183501_AndroidAPS](https://user-images.githubusercontent.com/45144129/73408724-75e01400-42fd-11ea-98eb-af06a94937f8.jpg)

**Comment by andyrozman** [comment] 2020-02-15 11:14
Seems like duplicate of #82

**Closed as completed** 2020-02-15 14:00 UTC
Labels: Duplicate
