### ISSUE TITLE
AAPS installed for "English" language on Dutch OS installation: Mixed English & Dutch screen texst

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#169] opened 2020-09-06 19:36 UTC
### AndroidAPS 2.7-omnipod-0.4.1-SNAPSHOT 
Remote: https://github.com/AAPS-Omnipod/AndroidAPS.git
commit #ac922316
Flavor: fullrelease

Phone: Samsung Galaxy A40 (Android 9.0)

### Problem description:
Phone OS installed for Dutch (NL) language, region NL
AndroidAPS installation for "English" (setup wizard)

Several locations where text is displayed in Dutch (NL) language, while English is expected.

* **TAB names**
* **Left hamburger menu** (all menu names)*
* OMNIPOD tab: Reservoir: "**Meer dan** 50E"
* Overview, sensor age: "1d11**u**" (expected ""1d11h")
* Progress on top of screen: "**Verbinding maken gedurende 25 s**"
* Alert: "HH:MM **Pomp niet beschikbaar**"
* Alerts on graphics display: "**Pomp niet beschikbaar**"
* Carbs suggestion: "31 **nodig**"
* Bolus wizard: "Profile <**Huidig**>"

Screenshots:

![IMG-20200906-WA0000](https://user-images.githubusercontent.com/45144129/92333821-bfa98d80-f088-11ea-91dd-3def2baf7c06.jpg)
![IMG-20200902-WA0002](https://user-images.githubusercontent.com/45144129/92333826-ca642280-f088-11ea-9057-11f233d474d2.jpg)
![IMG-20200902-WA0003](https://user-images.githubusercontent.com/45144129/92333828-cafcb900-f088-11ea-8b8d-eed781a6e41e.jpg)
![IMG-20200901-WA0003](https://user-images.githubusercontent.com/45144129/92333829-cafcb900-f088-11ea-9fa6-b56a862ed14d.jpg)
![IMG-20200901-WA0004](https://user-images.githubusercontent.com/45144129/92333830-cafcb900-f088-11ea-8f78-c2b697c1c414.jpg)
![IMG-20200901-WA0005](https://user-images.githubusercontent.com/45144129/92333831-cb954f80-f088-11ea-8f56-16782165aeee.jpg)
![IMG-20200901-WA0006](https://user-images.githubusercontent.com/45144129/92333832-cb954f80-f088-11ea-9076-f6bf5097dd16.jpg)
![IMG-20200901-WA0007](https://user-images.githubusercontent.com/45144129/92333834-cc2de600-f088-11ea-8bc1-f8ab1b258b51.jpg)
![IMG-20200902-WA0000](https://user-images.githubusercontent.com/45144129/92333835-ccc67c80-f088-11ea-96bb-1c58a247f3c1.jpg)
![IMG-20200902-WA0001](https://user-images.githubusercontent.com/45144129/92333836-ccc67c80-f088-11ea-9791-4d9c57e001e9.jpg)

**Comment by larsqvd** [comment] 2020-09-06 22:23
I can confirm this issue on my android 7.0 test phone, my regular (android 10) phone has english (OS) by default. Changing to any other language also does not work, it is fully stuck on dutch on my test phone.

**Comment by bartsopers** [comment] 2020-09-09 15:57
In the main AAPS repo, I saw a commit that removes the language selection from the Setup Wizard, so I guess that AAPS uses the phone's language now. We didn't merge the commit that removes the language selection from the Setup Wizard yet, so that's probably causing some confusion. I will make sure to have this commit merged before the 0.4 release.
Regarding English translations in another language: this means that a text hasn't been translated yet, so it uses the default (English) version of that text. Due to recent changes in the module structure, we lost all Omnipod translations temporarily. These will be restored (and probably updated) in a future merge from the main AAPS repo.

**Closed as completed** 2020-09-25 15:21 UTC
