### ISSUE TITLE
Screen layout caps text area while executing Pod de-activation

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#80] opened 2020-01-29 01:49 UTC
AndroidAPS 2.6-omnipod-0.2
Build EROS_0.2 (release)

### Problem:
Screen layout caps text area while executing Pod de-activation.
### Hardware:
Samsung S7, Screen resolution 1920x1080 (FHD)

### Additional info
See screen prints below:

![Screenshot_20200129-002847_AndroidAPS](https://user-images.githubusercontent.com/45144129/73321157-e295d880-4241-11ea-8660-8a5c34398407.jpg)

![Screenshot_20200129-002906_AndroidAPS](https://user-images.githubusercontent.com/45144129/73321167-e6295f80-4241-11ea-8a63-a132feab31ab.jpg)

**Comment by andyrozman** [comment] 2020-02-01 16:22
This is fixed (will be released with 0.3)

**Comment by andyrozman** [comment] 2020-02-15 10:27
Duplicate of #51

**Closed as completed** 2020-03-14 19:32 UTC
Labels: bug, AAPS Integration, 0.3
