### ISSUE TITLE
Unexpected crash/restart

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#167] opened 2020-09-06 17:42 UTC
### AndroidAPS 2.7-omnipod-0.4.1-SNAPSHOT 
Remote: https://github.com/AAPS-Omnipod/AndroidAPS.git
commit #503fc9dbf94139eab690e9fb84b7d628c5f692e2
Flavor: fullrelease

Phone:
Samsung S6 Edge (Android 7.0)

### Problem description:
AAPS unexpectedly did a crash/restart.
Logfiles included.
Time of incident approximately 14:45h (?)

[AndroidAPS_LOG_1599396401542_appscrashrestart.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/5180035/AndroidAPS_LOG_1599396401542_appscrashrestart.log.zip)

**Comment by bartsopers** [comment] 2020-09-09 14:52
Thanks for reporting. As discussed in PM. I'm closing this for now as I cannot reproduce this, can't find anything in Firebase and cannot find any clues in the provided log files.
In case the issue occurs again, please report.

**Closed as completed by bartsopers** 2020-09-09 14:52 UTC
