### ISSUE TITLE
Pump unreachable alert although option off

### ISSUE THREAD

**Issue by Kywalh** [AAPS-Omnipod/AndroidAPS-OLD#56] opened 2020-01-19 10:25 UTC
Having the Rileylink and the pod at 2 different sites at home, I have a pump unreachable alarm although the option is ticked off in the settings...

Once acknowledged, the alarm re-raises after some minutes

![Screenshot_20200119-112105](https://user-images.githubusercontent.com/28366579/72679307-3704bf80-3aae-11ea-91dc-32acae3a2fc5.jpg)
![Screenshot_20200119-112150](https://user-images.githubusercontent.com/28366579/72679309-3bc97380-3aae-11ea-967d-bd817a2ca953.jpg)

[AndroidAPS._2020-01-19_00-00-00_.1.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4082506/AndroidAPS._2020-01-19_00-00-00_.1.zip)

**Comment by bartsopers** [comment] 2020-01-19 12:15
This is actually by design. We chose to have a fixed pump unreachable warning, because once you use your pod with AAPS, there is no other way to control your pod, so it's important that the pod is reachable.
In a future version, we will remove the option to disable alerts, because as you found out, that option doesn't have an effect for the Omnipod driver.
Furthermore, recent changes in dev changed the alert sound behavior. That should make it possible to disable sounds for notifications. We'll merge these changes in a future test version.

I'll close this issue and create a new issue for removing the option to disable alerts.

**Closed as completed by bartsopers** 2020-01-19 12:15 UTC

**Comment by bartsopers** [comment] 2020-01-19 12:28
Opened #59 for this
