### ISSUE TITLE
Pod Failure - 064 ENCODER_COUNT_TOO_HIGH

### ISSUE THREAD

**Issue by cranetim** [AAPS-Omnipod/AndroidAPS-OLD#87] opened 2020-02-14 02:08 UTC
Pod failure occurred at approx 3:30pm 1.9 units into a 2.0 unit manual bolus.

AndroidAPS 2.6-omnipod-0.2
Build: EROS_0.2-2020.01.27-14:32
Flavor: fullrelease
Nightscout version: 0.10.3-master-20180805
Engineering mode enabled
 
[AndroidAPS_LOG_1581630722478.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4202310/AndroidAPS_LOG_1581630722478.log.zip)

**Comment by bartsopers** [comment] 2020-02-21 20:43
Discussed with @itsmojo. This is probably not directly caused by our driver. It could be related to a depleted battery, which could theoretically be caused by the driver issuing too many commands. However, I consider that unlikely as this is the first report of a 0x40 pod fault with a non-expired pod, so I will close this issue for now.

**Closed as completed by bartsopers** 2020-02-21 20:43 UTC
Labels: wontfix, Eros Communication
